---
dependencies:
  build_runner: ^2.4.13
  cached_network_image: ^3.4.1

  cloud_firestore: ^5.6.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  firebase_ui_firestore: ^1.7.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.0.17
  freezed: ^2.5.7
  get_it: ^8.0.3
  go_router: ^14.2.6
  hashtagable: ^2.3.0+1
  http: ^1.2.2
  image_picker: ^1.1.2
  injectable_generator: ^2.6.2
  intl: 0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  json_theme: ^7.0.0+3
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0
  timeago: ^3.7.0
  uuid: ^4.5.1
  video_player: ^2.9.5
description: A new Flutter project.
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
environment:
  sdk: '>=3.0.2 <4.0.0'
flutter:
  assets:
    - assets/users.json
    - assets/items.json
  uses-material-design: true
name: flutter_application_1
publish_to: none
version: 1.0.0+1