---
dependencies:
  build_runner: ^2.4.13
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.4.0
  flutter_lints: ^4.0.0
  flutter_svg: ^0.22.0
  freezed: ^2.5.7
  get_it: ^7.7.0
  go_router: ^14.2.6
  http: ^1.2.2
  image_picker: ^1.1.2
  injectable_generator: ^2.6.2
  intl: ^0.18.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  json_theme: ^7.0.0+3
  shimmer: ^3.0.0
  uuid: ^4.5.1
description: A new Flutter project.
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
environment:
  sdk: '>=3.0.2 <4.0.0'
flutter:
  assets:
    - assets/users.json
    - assets/items.json
  uses-material-design: true
name: flutter_application_1
publish_to: none
version: 1.0.0+1